/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AuthIndexRouteImport } from './routes/_auth/index'
import { Route as AuthAdministrationIndexRouteImport } from './routes/_auth/administration/index'
import { Route as AuthFinanceInvoicesIndexRouteImport } from './routes/_auth/finance/invoices/index'
import { Route as AuthAdministrationUtilizatoriIndexRouteImport } from './routes/_auth/administration/utilizatori/index'
import { Route as AuthAdministrationTipuriParteneriIndexRouteImport } from './routes/_auth/administration/tipuri-parteneri/index'
import { Route as AuthAdministrationTipuriArticoleIndexRouteImport } from './routes/_auth/administration/tipuri-articole/index'
import { Route as AuthAdministrationPersoaneIndexRouteImport } from './routes/_auth/administration/persoane/index'
import { Route as AuthAdministrationParteneriIndexRouteImport } from './routes/_auth/administration/parteneri/index'
import { Route as AuthAdministrationListePretIndexRouteImport } from './routes/_auth/administration/liste-pret/index'
import { Route as AuthAdministrationIerarhieParteneriIndexRouteImport } from './routes/_auth/administration/ierarhie-parteneri/index'
import { Route as AuthAdministrationCatalogArticoleIndexRouteImport } from './routes/_auth/administration/catalog-articole/index'
import { Route as AuthAdministrationArticoleIndexRouteImport } from './routes/_auth/administration/articole/index'
import { Route as AuthFinanceInvoicesInvoiceIdRouteImport } from './routes/_auth/finance/invoices/$invoiceId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAdministrationIndexRoute = AuthAdministrationIndexRouteImport.update({
  id: '/administration/',
  path: '/administration/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthFinanceInvoicesIndexRoute =
  AuthFinanceInvoicesIndexRouteImport.update({
    id: '/finance/invoices/',
    path: '/finance/invoices/',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthAdministrationUtilizatoriIndexRoute =
  AuthAdministrationUtilizatoriIndexRouteImport.update({
    id: '/administration/utilizatori/',
    path: '/administration/utilizatori/',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthAdministrationTipuriParteneriIndexRoute =
  AuthAdministrationTipuriParteneriIndexRouteImport.update({
    id: '/administration/tipuri-parteneri/',
    path: '/administration/tipuri-parteneri/',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthAdministrationTipuriArticoleIndexRoute =
  AuthAdministrationTipuriArticoleIndexRouteImport.update({
    id: '/administration/tipuri-articole/',
    path: '/administration/tipuri-articole/',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthAdministrationPersoaneIndexRoute =
  AuthAdministrationPersoaneIndexRouteImport.update({
    id: '/administration/persoane/',
    path: '/administration/persoane/',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthAdministrationParteneriIndexRoute =
  AuthAdministrationParteneriIndexRouteImport.update({
    id: '/administration/parteneri/',
    path: '/administration/parteneri/',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthAdministrationListePretIndexRoute =
  AuthAdministrationListePretIndexRouteImport.update({
    id: '/administration/liste-pret/',
    path: '/administration/liste-pret/',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthAdministrationIerarhieParteneriIndexRoute =
  AuthAdministrationIerarhieParteneriIndexRouteImport.update({
    id: '/administration/ierarhie-parteneri/',
    path: '/administration/ierarhie-parteneri/',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthAdministrationCatalogArticoleIndexRoute =
  AuthAdministrationCatalogArticoleIndexRouteImport.update({
    id: '/administration/catalog-articole/',
    path: '/administration/catalog-articole/',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthAdministrationArticoleIndexRoute =
  AuthAdministrationArticoleIndexRouteImport.update({
    id: '/administration/articole/',
    path: '/administration/articole/',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthFinanceInvoicesInvoiceIdRoute =
  AuthFinanceInvoicesInvoiceIdRouteImport.update({
    id: '/finance/invoices/$invoiceId',
    path: '/finance/invoices/$invoiceId',
    getParentRoute: () => AuthRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthIndexRoute
  '/login': typeof LoginRoute
  '/administration/': typeof AuthAdministrationIndexRoute
  '/finance/invoices/$invoiceId': typeof AuthFinanceInvoicesInvoiceIdRoute
  '/administration/articole/': typeof AuthAdministrationArticoleIndexRoute
  '/administration/catalog-articole/': typeof AuthAdministrationCatalogArticoleIndexRoute
  '/administration/ierarhie-parteneri/': typeof AuthAdministrationIerarhieParteneriIndexRoute
  '/administration/liste-pret/': typeof AuthAdministrationListePretIndexRoute
  '/administration/parteneri/': typeof AuthAdministrationParteneriIndexRoute
  '/administration/persoane/': typeof AuthAdministrationPersoaneIndexRoute
  '/administration/tipuri-articole/': typeof AuthAdministrationTipuriArticoleIndexRoute
  '/administration/tipuri-parteneri/': typeof AuthAdministrationTipuriParteneriIndexRoute
  '/administration/utilizatori/': typeof AuthAdministrationUtilizatoriIndexRoute
  '/finance/invoices/': typeof AuthFinanceInvoicesIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/': typeof AuthIndexRoute
  '/administration': typeof AuthAdministrationIndexRoute
  '/finance/invoices/$invoiceId': typeof AuthFinanceInvoicesInvoiceIdRoute
  '/administration/articole': typeof AuthAdministrationArticoleIndexRoute
  '/administration/catalog-articole': typeof AuthAdministrationCatalogArticoleIndexRoute
  '/administration/ierarhie-parteneri': typeof AuthAdministrationIerarhieParteneriIndexRoute
  '/administration/liste-pret': typeof AuthAdministrationListePretIndexRoute
  '/administration/parteneri': typeof AuthAdministrationParteneriIndexRoute
  '/administration/persoane': typeof AuthAdministrationPersoaneIndexRoute
  '/administration/tipuri-articole': typeof AuthAdministrationTipuriArticoleIndexRoute
  '/administration/tipuri-parteneri': typeof AuthAdministrationTipuriParteneriIndexRoute
  '/administration/utilizatori': typeof AuthAdministrationUtilizatoriIndexRoute
  '/finance/invoices': typeof AuthFinanceInvoicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/_auth/': typeof AuthIndexRoute
  '/_auth/administration/': typeof AuthAdministrationIndexRoute
  '/_auth/finance/invoices/$invoiceId': typeof AuthFinanceInvoicesInvoiceIdRoute
  '/_auth/administration/articole/': typeof AuthAdministrationArticoleIndexRoute
  '/_auth/administration/catalog-articole/': typeof AuthAdministrationCatalogArticoleIndexRoute
  '/_auth/administration/ierarhie-parteneri/': typeof AuthAdministrationIerarhieParteneriIndexRoute
  '/_auth/administration/liste-pret/': typeof AuthAdministrationListePretIndexRoute
  '/_auth/administration/parteneri/': typeof AuthAdministrationParteneriIndexRoute
  '/_auth/administration/persoane/': typeof AuthAdministrationPersoaneIndexRoute
  '/_auth/administration/tipuri-articole/': typeof AuthAdministrationTipuriArticoleIndexRoute
  '/_auth/administration/tipuri-parteneri/': typeof AuthAdministrationTipuriParteneriIndexRoute
  '/_auth/administration/utilizatori/': typeof AuthAdministrationUtilizatoriIndexRoute
  '/_auth/finance/invoices/': typeof AuthFinanceInvoicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/administration/'
    | '/finance/invoices/$invoiceId'
    | '/administration/articole/'
    | '/administration/catalog-articole/'
    | '/administration/ierarhie-parteneri/'
    | '/administration/liste-pret/'
    | '/administration/parteneri/'
    | '/administration/persoane/'
    | '/administration/tipuri-articole/'
    | '/administration/tipuri-parteneri/'
    | '/administration/utilizatori/'
    | '/finance/invoices/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/'
    | '/administration'
    | '/finance/invoices/$invoiceId'
    | '/administration/articole'
    | '/administration/catalog-articole'
    | '/administration/ierarhie-parteneri'
    | '/administration/liste-pret'
    | '/administration/parteneri'
    | '/administration/persoane'
    | '/administration/tipuri-articole'
    | '/administration/tipuri-parteneri'
    | '/administration/utilizatori'
    | '/finance/invoices'
  id:
    | '__root__'
    | '/_auth'
    | '/login'
    | '/_auth/'
    | '/_auth/administration/'
    | '/_auth/finance/invoices/$invoiceId'
    | '/_auth/administration/articole/'
    | '/_auth/administration/catalog-articole/'
    | '/_auth/administration/ierarhie-parteneri/'
    | '/_auth/administration/liste-pret/'
    | '/_auth/administration/parteneri/'
    | '/_auth/administration/persoane/'
    | '/_auth/administration/tipuri-articole/'
    | '/_auth/administration/tipuri-parteneri/'
    | '/_auth/administration/utilizatori/'
    | '/_auth/finance/invoices/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/administration/': {
      id: '/_auth/administration/'
      path: '/administration'
      fullPath: '/administration/'
      preLoaderRoute: typeof AuthAdministrationIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/finance/invoices/': {
      id: '/_auth/finance/invoices/'
      path: '/finance/invoices'
      fullPath: '/finance/invoices/'
      preLoaderRoute: typeof AuthFinanceInvoicesIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/administration/utilizatori/': {
      id: '/_auth/administration/utilizatori/'
      path: '/administration/utilizatori'
      fullPath: '/administration/utilizatori/'
      preLoaderRoute: typeof AuthAdministrationUtilizatoriIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/administration/tipuri-parteneri/': {
      id: '/_auth/administration/tipuri-parteneri/'
      path: '/administration/tipuri-parteneri'
      fullPath: '/administration/tipuri-parteneri/'
      preLoaderRoute: typeof AuthAdministrationTipuriParteneriIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/administration/tipuri-articole/': {
      id: '/_auth/administration/tipuri-articole/'
      path: '/administration/tipuri-articole'
      fullPath: '/administration/tipuri-articole/'
      preLoaderRoute: typeof AuthAdministrationTipuriArticoleIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/administration/persoane/': {
      id: '/_auth/administration/persoane/'
      path: '/administration/persoane'
      fullPath: '/administration/persoane/'
      preLoaderRoute: typeof AuthAdministrationPersoaneIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/administration/parteneri/': {
      id: '/_auth/administration/parteneri/'
      path: '/administration/parteneri'
      fullPath: '/administration/parteneri/'
      preLoaderRoute: typeof AuthAdministrationParteneriIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/administration/liste-pret/': {
      id: '/_auth/administration/liste-pret/'
      path: '/administration/liste-pret'
      fullPath: '/administration/liste-pret/'
      preLoaderRoute: typeof AuthAdministrationListePretIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/administration/ierarhie-parteneri/': {
      id: '/_auth/administration/ierarhie-parteneri/'
      path: '/administration/ierarhie-parteneri'
      fullPath: '/administration/ierarhie-parteneri/'
      preLoaderRoute: typeof AuthAdministrationIerarhieParteneriIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/administration/catalog-articole/': {
      id: '/_auth/administration/catalog-articole/'
      path: '/administration/catalog-articole'
      fullPath: '/administration/catalog-articole/'
      preLoaderRoute: typeof AuthAdministrationCatalogArticoleIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/administration/articole/': {
      id: '/_auth/administration/articole/'
      path: '/administration/articole'
      fullPath: '/administration/articole/'
      preLoaderRoute: typeof AuthAdministrationArticoleIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/finance/invoices/$invoiceId': {
      id: '/_auth/finance/invoices/$invoiceId'
      path: '/finance/invoices/$invoiceId'
      fullPath: '/finance/invoices/$invoiceId'
      preLoaderRoute: typeof AuthFinanceInvoicesInvoiceIdRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthIndexRoute: typeof AuthIndexRoute
  AuthAdministrationIndexRoute: typeof AuthAdministrationIndexRoute
  AuthFinanceInvoicesInvoiceIdRoute: typeof AuthFinanceInvoicesInvoiceIdRoute
  AuthAdministrationArticoleIndexRoute: typeof AuthAdministrationArticoleIndexRoute
  AuthAdministrationCatalogArticoleIndexRoute: typeof AuthAdministrationCatalogArticoleIndexRoute
  AuthAdministrationIerarhieParteneriIndexRoute: typeof AuthAdministrationIerarhieParteneriIndexRoute
  AuthAdministrationListePretIndexRoute: typeof AuthAdministrationListePretIndexRoute
  AuthAdministrationParteneriIndexRoute: typeof AuthAdministrationParteneriIndexRoute
  AuthAdministrationPersoaneIndexRoute: typeof AuthAdministrationPersoaneIndexRoute
  AuthAdministrationTipuriArticoleIndexRoute: typeof AuthAdministrationTipuriArticoleIndexRoute
  AuthAdministrationTipuriParteneriIndexRoute: typeof AuthAdministrationTipuriParteneriIndexRoute
  AuthAdministrationUtilizatoriIndexRoute: typeof AuthAdministrationUtilizatoriIndexRoute
  AuthFinanceInvoicesIndexRoute: typeof AuthFinanceInvoicesIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthIndexRoute: AuthIndexRoute,
  AuthAdministrationIndexRoute: AuthAdministrationIndexRoute,
  AuthFinanceInvoicesInvoiceIdRoute: AuthFinanceInvoicesInvoiceIdRoute,
  AuthAdministrationArticoleIndexRoute: AuthAdministrationArticoleIndexRoute,
  AuthAdministrationCatalogArticoleIndexRoute:
    AuthAdministrationCatalogArticoleIndexRoute,
  AuthAdministrationIerarhieParteneriIndexRoute:
    AuthAdministrationIerarhieParteneriIndexRoute,
  AuthAdministrationListePretIndexRoute: AuthAdministrationListePretIndexRoute,
  AuthAdministrationParteneriIndexRoute: AuthAdministrationParteneriIndexRoute,
  AuthAdministrationPersoaneIndexRoute: AuthAdministrationPersoaneIndexRoute,
  AuthAdministrationTipuriArticoleIndexRoute:
    AuthAdministrationTipuriArticoleIndexRoute,
  AuthAdministrationTipuriParteneriIndexRoute:
    AuthAdministrationTipuriParteneriIndexRoute,
  AuthAdministrationUtilizatoriIndexRoute:
    AuthAdministrationUtilizatoriIndexRoute,
  AuthFinanceInvoicesIndexRoute: AuthFinanceInvoicesIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
